### ISSUE TITLE
Mouse Menu click in rdp session - disconnect

### ISSUE THREAD

**Issue by mamema** [MaxWaldorf/guacamole#1]
Hi,

coming from oznu guacamole container, i've made the switch and discovered, that with older OS (eg: Windows 7), as soon as i click on start menu button, i get disconnected.
I find references (disconnect right mouse click) in google and thee it is a bug in freerdp 2.0
I disn't have this with the oznu container

Regards

Matt

**Comment by MaxWaldorf** [comment]
I am using FreeRDP 2.2 libraries through backport...

**Comment by mamema** [comment]
ok, was just a shot in the dark. But a i said, oznu container doesn't have the described issue. It's only with rdp connections.

**Comment by MaxWaldorf** [comment]
It is linked to FreeRDP libraries, nothing I can do on my end :)
