### ISSUE TITLE
RDP

### ISSUE THREAD

**Issue by mews-se** [MaxWaldorf/guacamole#11]
Has anyone managed to get an RDP-connection to work? And if so, how?

I've changed the registry edits on the host but no matter which combination of authentication methods I choose (this is on an AD)  I get connection refused.

According to Microsoft - they want you to log in with AzureAD\user@domain.tld but when I tried it on a windows-machine I got in with AzureAD\<localusername> instead.

So - has anyone managed, and if so how?

**Comment by MaxWaldorf** [comment]
There is a registry key to change in win 10 to make rdp fully work...

https://www.mogilowski.net/2020/03/24/windows-10-server-2016-rdp-work-with-guacamole/

**Comment by mews-se** [comment]
Yep, exactly those registry edits I mentioned. I will try to mess with the guac login method though!
