### ISSUE TITLE
Upgrade to 1.4.0

### ISSUE THREAD

**Issue by seantdavidson** [MaxWaldorf/guacamole#12]
What are the chances of upgrading this to the new version of 1.4.0? I am new to docker so I don't really have the ability to but will researching how to do it also.

**Comment by MaxWaldorf** [comment]
I'll give it a look to see how I could refactor that image...

Stay tuned

**Comment by MaxWaldorf** [comment]
Image updated

Initial tests are ok so far...

**Comment by seantdavidson** [comment]
Thanks, I am at work but was able to spin up a new image using this. I will try the upgrade when I get home.

**Comment by realivanjx** [comment]
just tried. so far so good.
