### ISSUE TITLE
error with permisions

### ISSUE THREAD

**Issue by tigger29900** [MaxWaldorf/guacamole#13]
I keep getting the below issue and for the life of me cannot figure out why the permissions wont work and wont reset

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-defaults.sh: executing... 
[cont-init.d] 30-defaults.sh: exited 0.
[cont-init.d] 40-postgres.sh: executing... 
chown: changing ownership of '/config/postgres': Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: could not access directory "/config/postgres": Permission denied
[cont-init.d] 40-postgres.sh: exited 1.
[cont-init.d] 50-extensions: executing... 
cat: /config/.database-version: No such file or directory
[cont-init.d] 50-extensions: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting postgres...
Starting guacamole guacd...
[services.d] done.
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
postgres: could not access the server configuration file "/config/postgres/postgresql.conf": Permission denied
guacd[268]: INFO:	Guacamole proxy daemon (guacd) version 1.3.0 started
guacd[268]: INFO:	Listening on host 127.0.0.1, port 4822
Starting postgres...
postgres: could not access the server configuration file "/config/postgres/postgresql.conf": Permission denied

**Comment by MaxWaldorf** [comment]
I never had the issue.
Please update to the latest image...

**Comment by MaxWaldorf** [comment]
continuing discussion on #14
