### ISSUE TITLE
enable "enable-environment-properties"

### ISSUE THREAD

**Issue by citricacid2** [MaxWaldorf/guacamole#15]
Would it be possible to enable "enable-environment-properties" in the guacamole.properties file so that any setting required can still be accessed if using a volume, and for overall convenience? Not great with docker yet, otherwise I would attempt a pr.

**Comment by MaxWaldorf** [comment]
I understand the request but this is a "non production ready" docker image...
So not being able to change the environment variables in docker / kubernetes doesn't make much sense.

**Comment by citricacid2** [comment]
Can you clarify? I am not sure I understood what you are trying to say.

**Comment by MaxWaldorf** [comment]
commited
