### ISSUE TITLE
Compile for ARMv7?

### ISSUE THREAD

**Issue by nickshanks347** [MaxWaldorf/guacamole#16]
This image is great - was just wondering if it was possible to compile for ARMv7?

I'd be happy to help if you need.

**Comment by MaxWaldorf** [comment]
Sorry base image isn't compatible with armv7...
________________________________
From: Nick ***@***.***>
Sent: Monday, January 31, 2022 6:09:03 PM
To: MaxWaldorf/guacamole ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxWaldorf/guacamole] Compile for ARMv7? (Issue #16)


This image is great - was just wondering if it was possible to compile for ARMv7?

I'd be happy to help if you need.
