### ISSUE TITLE
/init: 37: exec: s6-overlay-suexec: Exec format error

### ISSUE THREAD

**Issue by chunckky** [MaxWaldorf/guacamole#20]
Hi,

I try to use your docker image in a odroid n2+ (arm64), but i have this error :
/init: 37: exec: s6-overlay-suexec: Exec format error

this was my docker-compose file 
version: '3.7'
services:
  guacamole:
    image: abesnier/guacamole
    volumes:
      - type: bind
        source: /.../config
        target: /config
    ports:
      - 8080:8080/tcp

Could you help me ?
Thanks in advance.

**Comment by MaxWaldorf** [comment]
I am pretty sure you're not using my image...

`image: abesnier/guacamole`

**Comment by chunckky** [comment]
Sorry, I mixed my firefox tab when I subscribe to Github.
Your image is correct and work.
Thanks.

**Comment by abesnier** [comment]
I was doing some surveillance on my images (narcissistic, I know!), and I must say this message amused me.
