### ISSUE TITLE
Ghostscript installation

### ISSUE THREAD

**Issue by Benigans** [MaxWaldorf/guacamole#22]
Hi !

I installed your guacamole container and realized that it doesn't come with ghostscript installed (which is mandatory for the "print to pdf" option).
I ssh in the container and installed it manually ("apt update" and "apt install ghostscript") and it's working.

It would be great if the container came with ghostscript pre-installed.

Thanks !

**Comment by MaxWaldorf** [comment]
Yes you're right, I removed it because I never used it :D and thought it was non essential...

I will try to add it natively later on.

**Comment by MaxWaldorf** [comment]
testing in dev.

If successful, will integrate it

**Comment by MaxWaldorf** [comment]
Check version 1.4.2
⚠️ Compatibility with previous versions is broken...
