### ISSUE TITLE
Update this container image to commit past 20 april?

### ISSUE THREAD

**Issue by Macleykun** [MaxWaldorf/guacamole#24]
Hello!
I tried using this image and aside of the very easy setup, i always had this issue:
https://issues.apache.org/jira/browse/GUACAMOLE-1504

Now this is fixed, i wanted to ask if it's possible to update this image beyond that fix, so that ed25519 can be used.

That's all! I look forward to your reply!

**Comment by seantdavidson** [comment]
ED25519 keys are supported by Guacamole  at this time. There was rumbling that they may add it to the 1.5 version but no solid info on that along with no release date on 1.5

**Comment by MaxWaldorf** [comment]
Check version 1.4.2 as I upgraded to debian bullseye.
⚠️ Compatibility with previous versions is broken...

**Comment by Macleykun** [comment]
Using this template: https://raw.githubusercontent.com/novaspirit/pi-hosted/master/template/portainer-v2-arm64.json
i set it up just now, and while it's running fine, trying my private key (openssh format only, not PEM) seems to still ask for a keyphrase (which i didn't set on my private key).

@seantdavidson does it work for you?

**Comment by seantdavidson** [comment]
The openssh key formats don’t seem to work. I think you need PEM version. I am out of town now so can’t very the new version

**Comment by Macleykun** [comment]
RSA methode with pem works, took me a few tries
Will keep an eye on this still :)
