### ISSUE TITLE
need help migration concept for version 1.4.2

### ISSUE THREAD

**Issue by cybermcm** [MaxWaldorf/guacamole#27]
using your container for some time now, thank you for it.
Currently facing the "issue" of the updated postgres version. Managed to back up old database, but currently struggling to import it back.
any hint?
backup up ver 1.4.1, renamed postgres folder, started new ver 1.4.2. Then tried to reimport, but this won't work for me (database is locked...)

**Comment by cybermcm** [comment]
To answer my own question.
1. Version 1.4.1: run `docker exec -it guacamole pg_dump -U postgres -d guacamole_db -f /config/guac.sql` (creating backup)
2. stop container and rename postgres path to postgres_backup
3. stop container and switch to 1.4.2 -> start container
4. Enter container `docker exec -it guacamole bash`
5. drop current db `dropdb -f -U postgres guacamole_db;` and recreate db `createdb -U postgres guacamole_db;`
6. import backup `psql -U postgres guacamole_db < /config/guac.sql`
7. delete /config/guac.sql and postgres_backup path if you wish

**Comment by seantdavidson** [comment]
@cybermcm Thanks for the detailed info on this. It worked great. I don't have that many connections so I could redo them but this was the easiest way. Thanks.

**Comment by al3x1337** [comment]
> 

I tried this but on step 1 got this error back along the lines that guacamole_db was not found or can not connect.

My workaround was to update my docker-compose with an older image until this is fixed. I used maxwaldorf/guacamole:1.4.1

**Comment by seantdavidson** [comment]
@al3x1337 make sure that you are putting the name of your guacamole container in this line
`run docker exec -it <name of guacamole container> pg_dump -U postgres -d guacamole_db -f /config/guac.sql`

Other option is to use Portainer to connect to the container, and use the following if you connect with Portainer.
`pg_dump -U postgres -d guacamole_db -f /config/guac.sql`

**Comment by ovizii** [comment]
In case you have permission problems with the volume where PG is mounted on, the owner:group used by the system used to be 102:104 but is now 103:105

```
ls -aln 
drwx------  2 103 105     2 Sep 12 17:16 postgres                                                                                                    
drwx------ 19 102 104    26 Sep 10 17:50 postgres_old
```
