### ISSUE TITLE
cannot connect to ubuntu 22.04 ssh (ERROR: SSH handshake failed)

### ISSUE THREAD

**Issue by realivanjx** [MaxWaldorf/guacamole#29]
i got error when im trying to connect guacamole to my ubuntu 22.04 desktop. im hosting guacamole on raspberry pi 4 (ubuntu 20.04). it works fine when im trying to access my raspberry pi 4 through guacamole but errors when im trying to connect guacamole to my ubuntu 22.04 right after i put my username. for the mean time im connecting to my desktop via my raspberry pi (guacamole -> raspberry pi -> desktop). any help is appreciated. thanks.

**Comment by MaxWaldorf** [comment]
please check #8 if you're using a key

**Comment by realivanjx** [comment]
i dont use key authentication.

![image](https://user-images.githubusercontent.com/12814796/175770069-bd52e5c6-967f-4756-a1d9-1271f786de96.png)

those config also works well with my raspberry pi 4. i can also connect via normal ssh from my raspberry pi 4 to my desktop normally.

**Comment by MaxWaldorf** [comment]
I don't think there is anything specific to my docker image...
Maybe a bug directly in guacamole...

**Comment by alexgac** [comment]
Sorry to revive a zombie thread, but this is relevant: https://issues.apache.org/jira/browse/GUACAMOLE-1504
A guacamole dependency, the crypto library libgcrypt, wasn't implementing the newer format SSH keys correctly.  Apache is releasing an updated guac to address that.
