### ISSUE TITLE
RDP plugin not recognized

### ISSUE THREAD

**Issue by ersel** [MaxWaldorf/guacamole#3]
Having trouble establishing RDP connections, not sure if this is related to recent RDP changes on guacomole-server. 

https://github.com/apache/guacamole-server/pull/243

```
docker-guacamole-instance | guacd[271]: INFO:	Creating new client for protocol "rpd"
docker-guacamole-instance | guacd[271]: INFO:	Connection ID is "$74ae545d-51f4-48b9-aea5-f0cad693da48"
docker-guacamole-instance | guacd[533]: WARNING:	Support for protocol "rpd" is not installed
```

**Comment by MaxWaldorf** [comment]
I don't think this is related to this project. There are some registry keys to change on win10 clients in order for Guacamole RDP to work... Search, there are a couple articles covering that.


Cheers
