### ISSUE TITLE
connect web client with https?

### ISSUE THREAD

**Issue by dncpax** [MaxWaldorf/guacamole#30]
Hey there. Great work! Best way to have guacamole working in arm ever!
Wondering if and how can we make the web app work through https, instead of http:8080.

Thanks.

**Comment by MaxWaldorf** [comment]
Tomcat naturally expose port 8080

You would need a reverse proxy to achieve a redirect over 443 with SSL support.

**Comment by dncpax** [comment]
That's what I'm doing, but wondered if we could configure tomcat for https.
Thanks.
