### ISSUE TITLE
docker: no matching manifest for linux/arm/v8 in the manifest list entries.

### ISSUE THREAD

**Issue by ramoncio** [MaxWaldorf/guacamole#31]
Thanks for your nice image!
I can't install in an aarch64 device, I get this error:

`# docker run 
  -p 8080:8080 
  -v /storage/guacamole:/config 
  maxwaldorf/guacamole`
Unable to find image 'maxwaldorf/guacamole:latest' locally
latest: Pulling from maxwaldorf/guacamole
docker: no matching manifest for linux/arm/v8 in the manifest list entries.

` # uname -a`
Linux X88King 4.9.269 #1 SMP PREEMPT Wed Jul 27 09:00:53 CEST 2022 aarch64 GNU/Linux

**Comment by MaxWaldorf** [comment]
Well It works on RPI... So I don't know what exactly is happening for you specifically...
