### ISSUE TITLE
How to inject changes to guacamole.properties?

### ISSUE THREAD

**Issue by lenaxia** [MaxWaldorf/guacamole#32]
I'm trying to enable auth-header, and this requires that I add "http-auth-header: Remote-User" to guacamole.properties. What is the best way to inject this? 

While I can do this by hand, I'm trying to do this with IaC in kubernetes, so would much rather be able to have this done in an automated fashion.

**Comment by MaxWaldorf** [comment]
If you are using a persistent storage, I don't think this should be problematic to edit the file...

**Comment by lenaxia** [comment]
Ideally I'd like to have it set up without any manual intervention. I'm trying to get my containers in my kubernetes cluster to be fully configured upon deployment and for a piece of software as critical guacamole (since it's one of the primary entry points I use to my network) having it set up automatically is important.

**Comment by MaxWaldorf** [comment]
then create a standard file and inject it in your directory...

**Comment by MaxWaldorf** [comment]
If you have better ideas, please don't hesitate to submit a PR.
I will not investigate further on my end...
