### ISSUE TITLE
Adding more fonts to ssh sessions

### ISSUE THREAD

**Issue by ovizii** [MaxWaldorf/guacamole#33]
This is what I did, if there's an easier way, please correct me:

- installed additional fonts on the docker host system
- mapped the fonts folder into the container (see third volume)
- select desired (installed) font when configuring a ssh connection within guacamole

```
    volumes:                                                                                                                                         
      - './data:/config'                                                                                                                             
      - './shared-folder:/tmp/shared-folder'                                                                                                         
      - '/usr/share/fonts:/usr/share/fonts'
```

**Comment by MaxWaldorf** [comment]
Please submit a PR so I could include it in the main image...
(linking to local linux host isn't a solution)

It is obviously not critical feature...

**Comment by ovizii** [comment]
Of course, it's not critical, and I am unsure whether including a solution which adds fonts  in the main image is the best way as not everyone needs more fonts than your image initially provides. 
I think it's a nice and easy solution to add fonts to the image. Of course you wouldn't have to map - '/usr/share/fonts:/usr/share/fonts' - it could just be a local folder you add a few fonts to and map it to the image?

Anyway, I just wanted to leave this info here in case anyone requires more fonts, I don't think any changes are necessary. Thanks for your work and providing this image!
