### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by hsmptg** [MaxWaldorf/guacamole#34]
Hi
I installed on my Ubuntu home server your maxwaldorf/guacamole docker container.
By the way, the standard guacamole/guacamole image is not valid for my arm64 system, right?
After entering with the default guacadmin/guacadmin credentials, if I try to change the guacadmin password I get a "Permission denied" error.
I guess this is related with the permissions of the volume /home/ubuntu/docker/guacamole:/config, right?
But even making a chmod 777 to that folder the problem remains.
I noticed that a postgres subfolder with owner systemd-timesync messagebus with permission drwx------ is present!
Any tips on how to solve this?
Thanks

**Comment by MaxWaldorf** [comment]
I never had this issue but you can create a new user and disable a default one...

**Comment by hsmptg** [comment]
You are right!
Thanks!
