### ISSUE TITLE
Copy/paste problem to the settings editboxes

### ISSUE THREAD

**Issue by hsmptg** [MaxWaldorf/guacamole#35]
Hi
When I try to paste to any editbox of the settings web page using Firefox I always get a blank result.
If I do the same with Chrome I do not have that problem.
I even tried a Firefox on another PC and the result is the same: I can not paste the clipboard text that is cleared in the process.

The strange is that I have a guacamole in another server (this time using a guacamole/guacamole image since it is a amd64 server) and I do not have this copy/paste issue on both browsers (Chrome and Firefox).

Do you have any idea on what is causing this?
Regards

**Comment by MaxWaldorf** [comment]
are you using the aach64 image?

**Comment by hsmptg** [comment]
Yes, I am using ARM64.
Strange that in Chrome all works great even in the ssh cli.

**Comment by MaxWaldorf** [comment]
please test the "beta" (tag) container on Docker Hub...

**Comment by hsmptg** [comment]
Hi
Thanks for the reply.
With this beta version I see the same behaviour.
Note that this is probably a browser issue since I only see it in Firefox and not in Chrome (or Edge or Opera).
In all these last three browsers I am able to allow/block clipboard "interactions" but with Firefox it seems that is always blocked.
I know that Guacamole has a clipboard "tab" (accessed by pressing Ctrl+Alt+Left_Shift) that works also with Firefox but that is a very time consuming procedure.
Regards

**Comment by hsmptg** [comment]
OK thanks!
By the way, maybe you can think: if Chrome, Edge and Opera works OK, why not to use them instead?
Well Firefox is the only browser I know that allow multiple "picture-in-picture" of streaming videos which is great!
Bye and thanks for all your work!

**Comment by hsmptg** [comment]
Meanwhile I think I found the Firefox setting that allow the direct use of the clipboard.
Just go to "about:config" and change the "dom.events.testing.asyncClipboard" to true.
