### ISSUE TITLE
Cannot paste into Guacamole WebGUI

### ISSUE THREAD

**Issue by edofullin** [MaxWaldorf/guacamole#36]
As title says, using image maxwaldorf/guacamole:latest paste seems to be not working. 
I'm not talking into RDP or SSH sessions in guacamole but into guacamole <input> fields (including login, settings, session clipboard, etc) like in those websites where you cannot copy-paste the confirm email or password text field.

I'm using a custom guacamole.properties to enable openid and use an external postgres DBMS (the future plan is to compile a custom image without postgres, but I have this problem on both the custom image and the original) 
  
I do not know where to look to solve this, tried with multiple browser, clearing cache and from multiple computers. 

Thanks in advance!

Custom guacamole.properties:

```
postgresql-hostname: 172.28.1.2
postgresql-port: 5432
postgresql-database: newguacamole
postgresql-username: guacamole
postgresql-password: XXXXXXXXX
postgresql-auto-create-accounts: true

openid-authorization-endpoint: https://XXXXXX/realms/XXXXXX/protocol/openid-connect/auth
openid-jwks-endpoint: https://XXXXXX/realms/XXXXXX/protocol/openid-connect/certs
openid-issuer: https://XXXXXX/realms/XXXXXX
openid-client-id: guacamole
openid-redirect-uri: https://XXXXXX
openid-username-claim-type: preferred_username
openid-scope: openid email profile
openid-groups-claim-type: groups

extension-priority: *, openid
enable-clipboard-integration: true
```

**Comment by MaxWaldorf** [comment]
https://thecelebtimes.com/how-do-you-copy-and-paste-in-guacamole
