### ISSUE TITLE
how to modify page index please

### ISSUE THREAD

**Issue by aymen6000** [MaxWaldorf/guacamole#38]
how to modify page index please

**Comment by aymen6000** [comment]
i want to modify the page index  main 
for exemple i want to change the Image and the text "APACHE guacamole"

**Comment by MaxWaldorf** [comment]
Sorry, not editable...

**Comment by giegiey** [comment]
> i want to modify the page index main for exemple i want to change the Image and the text "APACHE guacamole"

Edit text
/usr/local/tomcat/webapps/ROOT/translations/en.json
