### ISSUE TITLE
guacamole-auth-json extension

### ISSUE THREAD

**Issue by calebcoverdale** [MaxWaldorf/guacamole#5]
Hey there! 

I was wondering if you could add in the guacamole-auth-json extension into the docker container? 

Thanks!

**Comment by MaxWaldorf** [comment]
Here are the module that are available...

https://apache.mediamirrors.org/guacamole/1.3.0/binary/

That's it...

**Comment by netbix** [comment]
Hello !

excellent to have resumed the oznu project!
why the guacamole-auth-header-1.3.0.tar.gz module is not inside the extensions-available folder?

![immagine](https://user-images.githubusercontent.com/66208491/127656809-526aaebe-4315-4bab-a445-95493cb5872c.png)

and is that correct?
in the apache project there is not ....

![immagine](https://user-images.githubusercontent.com/66208491/127657017-2e5cd091-8f7e-4ebb-81c0-f802cc66dee0.png)

**Comment by MaxWaldorf** [comment]
The docker script looks for 1.3.0 compatible versions...
Not sure if the auth header is compatible with 1.2.0 since this is flagged on an other version.
