### ISSUE TITLE
v1.5.0 cannot start with error

### ISSUE THREAD

**Issue by fate8383** [MaxWaldorf/guacamole#55]
Starting guacamole client...
992
/usr/local/tomcat/bin/catalina.sh: line 421: /usr/local/openjdk-8/bin/java: No such file or directory
993
2023-03-17 09:50:52.694 UTC [5753] FATAL:  role "root" does not exist
994
/var/run/postgresql:5432 - accepting connections

**Comment by MaxWaldorf** [comment]
please follow #53
