### ISSUE TITLE
1.5.0 Authentication error while login

### ISSUE THREAD

**Issue by Mitch187** [MaxWaldorf/guacamole#58]
Hi,

`18-Mar-2023 05:01:12.225 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/8.5.82]
18-Mar-2023 05:01:12.247 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
18-Mar-2023 05:01:13.911 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
05:01:14.528 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
05:01:14.665 [localhost-startStop-1] INFO  o.a.g.GuacamoleServletContextListener - Read configuration parameters from "/config/guacamole/guacamole.properties".
05:01:14.667 [localhost-startStop-1] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
05:01:15.078 [localhost-startStop-1] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
18-Mar-2023 05:01:16.165 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [3,918] ms
18-Mar-2023 05:01:16.168 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
18-Mar-2023 05:01:16.277 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 4079 ms
07:57:48.938 [http-nio-8080-exec-10] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [37.201.221.64, 192.168.15.5] for user "guacadmin" failed.
07:57:53.982 [http-nio-8080-exec-8] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [37.201.221.64, 192.168.15.5] for user "guacadmin" failed.
07:58:09.757 [http-nio-8080-exec-8] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [37.201.221.64, 192.168.15.5] for user "guacadmin" failed.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-defaults.sh: executing... 
[cont-init.d] 30-defaults.sh: exited 0.
[cont-init.d] 40-postgres.sh: executing... 
Database already configured
[cont-init.d] 40-postgres.sh: exited 0.
[cont-init.d] 50-extensions: executing... 
[cont-init.d] 50-extensions: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting guacamole guacd...
Starting postgres...
[services.d] done.
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
guacd[268]: INFO:	Guacamole proxy daemon (guacd) version 1.5.0 started
guacd[268]: INFO:	Listening on host 0.0.0.0, port 4822
2023-03-18 07:58:42.693 UTC [269] LOG:  starting PostgreSQL 13.9 (Debian 13.9-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-03-18 07:58:42.694 UTC [269] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-03-18 07:58:42.694 UTC [269] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2023-03-18 07:58:42.694 UTC [269] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2023-03-18 07:58:42.702 UTC [269] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-03-18 07:58:42.711 UTC [282] LOG:  database system was interrupted; last known up at 2023-03-18 05:01:10 UTC
2023-03-18 07:58:43.021 UTC [282] LOG:  database system was not properly shut down; automatic recovery in progress
2023-03-18 07:58:43.028 UTC [282] LOG:  redo starts at 0/173C9D8
2023-03-18 07:58:43.028 UTC [282] LOG:  invalid record length at 0/173CA10: wanted 24, got 0
2023-03-18 07:58:43.028 UTC [282] LOG:  redo done at 0/173C9D8
2023-03-18 07:58:43.055 UTC [269] LOG:  database system is ready to accept connections
2023-03-18 07:58:43.676 UTC [290] FATAL:  role "root" does not exist
/var/run/postgresql:5432 - accepting connections
Starting guacamole client...
18-Mar-2023 07:58:44.244 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.82
18-Mar-2023 07:58:44.246 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 8 2022 21:26:07 UTC
18-Mar-2023 07:58:44.246 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.82.0
18-Mar-2023 07:58:44.246 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
18-Mar-2023 07:58:44.246 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.85-1-pve
18-Mar-2023 07:58:44.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
18-Mar-2023 07:58:44.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
18-Mar-2023 07:58:44.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_342-b07
18-Mar-2023 07:58:44.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
18-Mar-2023 07:58:44.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
18-Mar-2023 07:58:44.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
18-Mar-2023 07:58:44.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
18-Mar-2023 07:58:44.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
18-Mar-2023 07:58:44.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
18-Mar-2023 07:58:44.249 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
18-Mar-2023 07:58:44.249 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
18-Mar-2023 07:58:44.249 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
18-Mar-2023 07:58:44.252 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
18-Mar-2023 07:58:44.252 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
18-Mar-2023 07:58:44.253 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
18-Mar-2023 07:58:44.253 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.35] using APR version [1.7.0].
18-Mar-2023 07:58:44.253 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [{4}].
18-Mar-2023 07:58:44.253 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
18-Mar-2023 07:58:44.256 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1n  15 Mar 2022]
18-Mar-2023 07:58:44.326 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
18-Mar-2023 07:58:44.345 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 495 ms
18-Mar-2023 07:58:44.371 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
18-Mar-2023 07:58:44.372 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/8.5.82]
18-Mar-2023 07:58:44.393 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
18-Mar-2023 07:58:45.699 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
07:58:46.204 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
07:58:46.324 [localhost-startStop-1] INFO  o.a.g.GuacamoleServletContextListener - Read configuration parameters from "/config/guacamole/guacamole.properties".
07:58:46.326 [localhost-startStop-1] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
07:58:46.732 [localhost-startStop-1] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
18-Mar-2023 07:58:47.808 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [3,414] ms
18-Mar-2023 07:58:47.810 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
18-Mar-2023 07:58:47.828 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 3482 ms
07:59:10.549 [http-nio-8080-exec-1] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [37.201.221.64, 192.168.15.5] for user "guacadmin" failed.
08:02:11.550 [http-nio-8080-exec-3] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [37.201.221.64, 192.168.15.5] for user "guacadmin" failed.
18-Mar-2023 08:05:43.926 INFO [http-nio-8080-exec-8] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target [/#login ]. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:517)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:513)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:882)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1693)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)

Before Update, it works perfektly.

Best Regards,
Mitch`

**Comment by MaxWaldorf** [comment]
pleasevfollow #53
