### ISSUE TITLE
Impossible to activate auth-totp 

### ISSUE THREAD

**Issue by SirOch27** [MaxWaldorf/guacamole#6]
Hello,

I  have an issue when i tried to change the authentication method.
When i follow the documentation to activate auth-totp for example, it's not working.
I copy the file "guacamole-auth-totp-1.3.0.jar" from "extensions-available" to "extensions" and i remove the file "guacamole-auth-jdbc-postgresql-1.3.0.jar"
I modify the file "guacamole.properties:" to use totp.
When i restart the container, the file "guacamole-auth-totp-1.3.0.jar" is always replaced by "guacamole-auth-jdbc-postgresql-1.3.0.jar".
I have the same issue when i try any other authentication method.

Do i do something wrong ?
Can you have a look please ?

**Comment by MaxWaldorf** [comment]
you just need to declare the auth-topt extension in your docker script...
Nothing more.

I use it and it works perfectly!
