### ISSUE TITLE
SSH connection with private key not working

### ISSUE THREAD

**Issue by carfanatic93** [MaxWaldorf/guacamole#62]
Is there a way to show the logs when I try to connect via ssh and private key ?

"docker logs guacamole" shows as last line "container started" but when I try to connect, nothing happens in the logs.

I got the right format of the private key already set up in the connection settings, but it is still not connecting.

Maybe somebody can help me?

**Comment by MaxWaldorf** [comment]
new 1.5.0 image coming up...
this time, we should be good for a while!
